### ISSUE TITLE
Cannot set ruff path in helix

### ISSUE THREAD

**Issue by thomasaarholt** [LaBatata101/sith-language-server#7]
Thanks for writing sith! Really exciting to see more products in this space!

I'm using [helix](https://github.com/helix-editor/helix), a vim-like editor. Ruff's example LSP config for helix is [here](https://docs.astral.sh/ruff/editors/setup/#helix), which is a config setup that I think you're copying with sith. I thought I could contribute to the readme with a helix setup.

Could you show us a working sith vim config for setting the ruff path? I'm unable to get it to work. Here's my current config, which is added to the `languages.toml` helix config file (which augments the [default one](https://github.com/helix-editor/helix/blob/master/languages.toml))

```toml
[language-server.sith-lsp]
command = "sith-lsp"

[language-server.sith-lsp.config.settings.sith.ruff]
path = '/Users/thomas/codes/sith-test/.venv/bin/ruff'

[[language]]
name = "python"
language-servers = [ 
  "sith-lsp",
]
```
I'm specifying the ruff one mainly to understand how to configure sith. That config has a warning that appears when I open helix: `Ruff path was not set in settings!`, which provided nice direct feedback.

I normally use ruff through its direct LSP interface, and will probably continue to do so. Is there a particular reason "contain" ruff inside your own LSP?

**Comment by LaBatata101** [comment]
Thanks for trying it out!

To fix your issue you can just ommit the `sith` part of the config
`[language-server.sith-lsp.config.settings.sith.ruff]` -> `[language-server.sith-lsp.config.settings.ruff]`.

> I normally use ruff through its direct LSP interface, and will probably continue to do so. Is there a particular reason "contain" ruff inside your own LSP?

It's to provide linting and formatting features out of the box in SithLSP. There's also the convenience of not having to deal with two configurations separately. I've released a new version that allows you disable the ruff integration with
```toml
[language-server.sith-lsp.config.settings.ruff]
enable = false
```
